name: Run Tests for Skiko

on:
  push:
    branches:
      - skiko
      - skiko-m*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            configs:
              - gl
              - gldft
              - glmsaa4
              - gldmsaa
            matches:
              # From infra/bots/gen_tasks_logic/dm_flags.go
              - "~^SkRuntimeBlender_Ganesh$" # skbug.com/458193911
              - "~^BigImageTest_Ganesh$"
          - os: macos-15
            configs:
              - mtl
            matches:
              # From infra/bots/gen_tasks_logic/dm_flags.go
              - "~^BigImageTest_Ganesh$"
              - "~^GrMeshTest$" # skbug.com/40038854
              - "~^DMSAA_aa_dst_read_after_dmsaa$" # b/438450848
              - "~^DMSAA_dst_read$" # b/438450848
              - "~^SurfacePartialDraw_Gpu$" # b/438450848
              - "~^FilterResult_ganesh_RescaleWithColorFilter$" # b/438450848
              - "~^FilterResult_ganesh_RescaleWithTransform$" # b/438450848
              - "~^FilterResult_ganesh_RescaleWithTileMode$" # b/438450848
              - "~^FilterResult_ganesh_ColorFilterBetweenCrops$" # b/438450848
              - "~^FilterResult_ganesh_TransformAndTile$" # b/438450848
              - "~^FilterResult_ganesh_PeriodicTileCrops$" # b/438450848
              - "~^FilterResult_ganesh_IntersectingCrops$" # b/438450848
              - "~^FilterResult_ganesh_CropDisjointFromSourceAndOutput$" # b/438450848
              - "~^FilterResult_ganesh_Crop$" # b/438450848
              # Extra GitHub Actions workarounds
              - "~^ProcessorCloneTest$" # flaky
              - "~^FilterResult_ganesh_CroppedTransformedTransparencyAffectingColorFilter$"
              - "~^FilterResult_ganesh_CroppedTransformedColorFilter$"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Set up Python 3
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.9'

      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          ./tools/install_dependencies.sh --yes

      - name: Run git-sync-deps (skia)
        run: |
          python3 tools/git-sync-deps

      - name: Install Ninja
        run: |
          python3 bin/fetch-ninja

      - name: Build skia DM
        run: |
          bin/gn gen out/Debug
          ./third_party/ninja/ninja -C out/Debug dm -j 8

      - name: Run tests
        run: |
          python3 .github/scripts/run_dm_tests_using_bot_config.py \
            --configs-json '${{ toJSON(matrix.configs) }}' \
            --matches-json '${{ toJSON(matrix.matches) }}'
